In [8]:
import numpy as np #imports pandas with pd alias (common convention), can now refer to it using np

In [9]:
#Creating a numpy array and assigning it to variable "arr", then printing the array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
#Arrays of Different Dimensions
arr0 = np.array(42) #0-D array
print(arr0)

arr1 = np.array([1,2,3]) #1-D array
print(arr1)

arr2 = np.array([[1,2,3],[4,5,6]]) #2-D Array
print(arr2)

arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]]) #3-D Array
print(arr3)
print(arr3.ndim) #finds number of dimensions

42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [18]:
#Slicing Arrays
arr_slice = [1,2,3,4,5,6,7,8,9,10]
print(arr_slice[1::3]) #slices array in the form [start:end:step], excludes end index, step
print(arr_slice[-5::]) #negative slicing, starts at 5th index from the end and print until the end inclusive (since left blank)

arr_2d_slice = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d_slice[2, -3:-1]) #elements -3 to -1 in array element 2 ([1,2,3] is array element 0, [7,8,9] is array element 2, so it prints the third-last to last (not including the last since last was not left blank))
print(arr_2d_slice[0:2,0:2]) #elements 0 to 1 from 2d array elements 0 and 1

[2, 5, 8]
[6, 7, 8, 9, 10]
[7 8]
[[1 2]
 [4 5]]


In [25]:
#Copying/Viewing the Array - view and base are less important
array1 = np.array([1,2,3,4,5])
array_copy = array1.copy() #creates a copy where changes will be independent of original, copy owns data
array_type = array1.astype("U21") #copy of array where you can specify new datatype, copy owns data
array1 = np.array([4000])
print(array1)
print(array_copy[0])

[4000]
1


In [27]:
#Shape of the Array
array_ex = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_ex.shape)
arr5d = np.array([1,2,3], ndmin = 5)
print(arr5d.shape)

(3, 3)
(1, 1, 1, 1, 3)


In [30]:
#Reshaping the Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) #1D array with shape 1 row x 12 columns
arr_resized = arr.reshape(4,3) #2D array with shape 4 rows x 3 columns
print(arr_resized)
arr_resized2 = arr.reshape(3,2,2) #3D array of size 3x2x2
print(arr_resized2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [37]:
#Iterating Arrays
arr1d = np.array([1,2,3])
for x in arr1d:
    print(x)

arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in arr3d:
    for y in x:
        for z in y:
            print(z)

for x in np.nditer(arr3d): #nditer() can be used to prevent using numerous nested for loops
    print(x)

for x in np.nditer(arr3d[0:2,0:2,0:1:]): #slicing
    print(x)


for ind, x in np.ndenumerate(arr3d): #to print the index along with the value
    print(ind, x)

1
2
3
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
3
5
7
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [40]:
#Joining Arrays
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
print(ar1)
print(ar2)
print(np.concatenate((ar1,ar2))) #prints joint array

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [44]:
#Splitting Arrays
arr = np.array([1,2,3,4,5,6])
print(np.split(arr,3)) #returned value is a list of 3 arrays, must result in an even division
arsplit = np.array_split(arr,5) #array_split returns an array of arrays and allows for non-even division of elements
print(arsplit)
print(arsplit[0][1])


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
2


In [46]:
#Searching Arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr %2 == 0) #prints index locations where element divided by two has a remainder of 0 (i.e. element is even)
print(x)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 6.8) #used for sorted arrays and returns index location where value should go
print(x)

(array([1, 3, 5, 6]),)
1


In [48]:
#Sorting Arrays
arr = np.array(['banana', 'carrot', 'apple'])
print(np.sort(arr)) #sorts element in array alphabetically in ascending order

arr1 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr1)) #sorts numbers in each 1D array in ascending order

['apple' 'banana' 'carrot']
[[2 3 4]
 [0 1 5]]


In [51]:
#Filtering Arrays - done using a boolean index list
arr = np.array([11, 23, 41, 42, 65, 23, 75, 234, 54, 23 ,234, 65, 23, 43, 12, 43]) #array or random numbers
boo_arr = [] #empty boolean array
for x in arr:
    if x>50:
        boo_arr.append(True) #if value in arr is greater than 50 adds "True" element to boolean array
    else:
        boo_arr.append(False) #otherwise adds "False" element to boolean array
filtered_arr = arr[boo_arr] #new array filtered_list is equal to the array "arr" with the boolean filter applied (i.e. if true the element will be added to filtered_list and if false will not be added)
print(boo_arr) #Prints list of boolean values
print(filtered_arr) #prints the filtered array

#simple way to achieve same task as above
simple_filter = arr < 50
newarr = arr[simple_filter]
print(newarr)

[False, False, False, False, True, False, True, True, True, False, True, True, False, False, False, False]
[ 65  75 234  54 234  65]
[11 23 41 42 23 23 23 43 12 43]
